// https://registry.terraform.io/providers/hashicorp/azurerm/4.3.0/docs/resources/voice_services_communications_gateway
// generated from terraform resource schema

import { Construct } from 'constructs';
import * as cdktf from 'cdktf';

// Configuration

export interface VoiceServicesCommunicationsGatewayConfig extends cdktf.TerraformMetaArguments {
  /**
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/azurerm/4.3.0/docs/resources/voice_services_communications_gateway#api_bridge VoiceServicesCommunicationsGateway#api_bridge}
  */
  readonly apiBridge?: string;
  /**
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/azurerm/4.3.0/docs/resources/voice_services_communications_gateway#auto_generated_domain_name_label_scope VoiceServicesCommunicationsGateway#auto_generated_domain_name_label_scope}
  */
  readonly autoGeneratedDomainNameLabelScope?: string;
  /**
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/azurerm/4.3.0/docs/resources/voice_services_communications_gateway#codecs VoiceServicesCommunicationsGateway#codecs}
  */
  readonly codecs: string;
  /**
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/azurerm/4.3.0/docs/resources/voice_services_communications_gateway#connectivity VoiceServicesCommunicationsGateway#connectivity}
  */
  readonly connectivity: string;
  /**
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/azurerm/4.3.0/docs/resources/voice_services_communications_gateway#e911_type VoiceServicesCommunicationsGateway#e911_type}
  */
  readonly e911Type: string;
  /**
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/azurerm/4.3.0/docs/resources/voice_services_communications_gateway#emergency_dial_strings VoiceServicesCommunicationsGateway#emergency_dial_strings}
  */
  readonly emergencyDialStrings?: string[];
  /**
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/azurerm/4.3.0/docs/resources/voice_services_communications_gateway#id VoiceServicesCommunicationsGateway#id}
  *
  * Please be aware that the id field is automatically added to all resources in Terraform providers using a Terraform provider SDK version below 2.
  * If you experience problems setting this value it might not be settable. Please take a look at the provider documentation to ensure it should be settable.
  */
  readonly id?: string;
  /**
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/azurerm/4.3.0/docs/resources/voice_services_communications_gateway#location VoiceServicesCommunicationsGateway#location}
  */
  readonly location: string;
  /**
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/azurerm/4.3.0/docs/resources/voice_services_communications_gateway#microsoft_teams_voicemail_pilot_number VoiceServicesCommunicationsGateway#microsoft_teams_voicemail_pilot_number}
  */
  readonly microsoftTeamsVoicemailPilotNumber?: string;
  /**
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/azurerm/4.3.0/docs/resources/voice_services_communications_gateway#name VoiceServicesCommunicationsGateway#name}
  */
  readonly name: string;
  /**
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/azurerm/4.3.0/docs/resources/voice_services_communications_gateway#on_prem_mcp_enabled VoiceServicesCommunicationsGateway#on_prem_mcp_enabled}
  */
  readonly onPremMcpEnabled?: boolean | cdktf.IResolvable;
  /**
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/azurerm/4.3.0/docs/resources/voice_services_communications_gateway#platforms VoiceServicesCommunicationsGateway#platforms}
  */
  readonly platforms: string[];
  /**
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/azurerm/4.3.0/docs/resources/voice_services_communications_gateway#resource_group_name VoiceServicesCommunicationsGateway#resource_group_name}
  */
  readonly resourceGroupName: string;
  /**
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/azurerm/4.3.0/docs/resources/voice_services_communications_gateway#tags VoiceServicesCommunicationsGateway#tags}
  */
  readonly tags?: { [key: string]: string };
  /**
  * service_location block
  *
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/azurerm/4.3.0/docs/resources/voice_services_communications_gateway#service_location VoiceServicesCommunicationsGateway#service_location}
  */
  readonly serviceLocation: VoiceServicesCommunicationsGatewayServiceLocation[] | cdktf.IResolvable;
  /**
  * timeouts block
  *
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/azurerm/4.3.0/docs/resources/voice_services_communications_gateway#timeouts VoiceServicesCommunicationsGateway#timeouts}
  */
  readonly timeouts?: VoiceServicesCommunicationsGatewayTimeouts;
}
export interface VoiceServicesCommunicationsGatewayServiceLocation {
  /**
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/azurerm/4.3.0/docs/resources/voice_services_communications_gateway#allowed_media_source_address_prefixes VoiceServicesCommunicationsGateway#allowed_media_source_address_prefixes}
  */
  readonly allowedMediaSourceAddressPrefixes?: string[];
  /**
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/azurerm/4.3.0/docs/resources/voice_services_communications_gateway#allowed_signaling_source_address_prefixes VoiceServicesCommunicationsGateway#allowed_signaling_source_address_prefixes}
  */
  readonly allowedSignalingSourceAddressPrefixes?: string[];
  /**
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/azurerm/4.3.0/docs/resources/voice_services_communications_gateway#esrp_addresses VoiceServicesCommunicationsGateway#esrp_addresses}
  */
  readonly esrpAddresses?: string[];
  /**
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/azurerm/4.3.0/docs/resources/voice_services_communications_gateway#location VoiceServicesCommunicationsGateway#location}
  */
  readonly location: string;
  /**
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/azurerm/4.3.0/docs/resources/voice_services_communications_gateway#operator_addresses VoiceServicesCommunicationsGateway#operator_addresses}
  */
  readonly operatorAddresses: string[];
}

export function voiceServicesCommunicationsGatewayServiceLocationToTerraform(struct?: VoiceServicesCommunicationsGatewayServiceLocation | cdktf.IResolvable): any {
  if (!cdktf.canInspect(struct) || cdktf.Tokenization.isResolvable(struct)) { return struct; }
  if (cdktf.isComplexElement(struct)) {
    throw new Error("A complex element was used as configuration, this is not supported: https://cdk.tf/complex-object-as-configuration");
  }
  return {
    allowed_media_source_address_prefixes: cdktf.listMapper(cdktf.stringToTerraform, false)(struct!.allowedMediaSourceAddressPrefixes),
    allowed_signaling_source_address_prefixes: cdktf.listMapper(cdktf.stringToTerraform, false)(struct!.allowedSignalingSourceAddressPrefixes),
    esrp_addresses: cdktf.listMapper(cdktf.stringToTerraform, false)(struct!.esrpAddresses),
    location: cdktf.stringToTerraform(struct!.location),
    operator_addresses: cdktf.listMapper(cdktf.stringToTerraform, false)(struct!.operatorAddresses),
  }
}


export function voiceServicesCommunicationsGatewayServiceLocationToHclTerraform(struct?: VoiceServicesCommunicationsGatewayServiceLocation | cdktf.IResolvable): any {
  if (!cdktf.canInspect(struct) || cdktf.Tokenization.isResolvable(struct)) { return struct; }
  if (cdktf.isComplexElement(struct)) {
    throw new Error("A complex element was used as configuration, this is not supported: https://cdk.tf/complex-object-as-configuration");
  }
  const attrs = {
    allowed_media_source_address_prefixes: {
      value: cdktf.listMapperHcl(cdktf.stringToHclTerraform, false)(struct!.allowedMediaSourceAddressPrefixes),
      isBlock: false,
      type: "set",
      storageClassType: "stringList",
    },
    allowed_signaling_source_address_prefixes: {
      value: cdktf.listMapperHcl(cdktf.stringToHclTerraform, false)(struct!.allowedSignalingSourceAddressPrefixes),
      isBlock: false,
      type: "set",
      storageClassType: "stringList",
    },
    esrp_addresses: {
      value: cdktf.listMapperHcl(cdktf.stringToHclTerraform, false)(struct!.esrpAddresses),
      isBlock: false,
      type: "set",
      storageClassType: "stringList",
    },
    location: {
      value: cdktf.stringToHclTerraform(struct!.location),
      isBlock: false,
      type: "simple",
      storageClassType: "string",
    },
    operator_addresses: {
      value: cdktf.listMapperHcl(cdktf.stringToHclTerraform, false)(struct!.operatorAddresses),
      isBlock: false,
      type: "set",
      storageClassType: "stringList",
    },
  };

  // remove undefined attributes
  return Object.fromEntries(Object.entries(attrs).filter(([_, value]) => value !== undefined && value.value !== undefined));
}

export class VoiceServicesCommunicationsGatewayServiceLocationOutputReference extends cdktf.ComplexObject {
  private isEmptyObject = false;
  private resolvableValue?: cdktf.IResolvable;

  /**
  * @param terraformResource The parent resource
  * @param terraformAttribute The attribute on the parent resource this class is referencing
  * @param complexObjectIndex the index of this item in the list
  * @param complexObjectIsFromSet whether the list is wrapping a set (will add tolist() to be able to access an item via an index)
  */
  public constructor(terraformResource: cdktf.IInterpolatingParent, terraformAttribute: string, complexObjectIndex: number, complexObjectIsFromSet: boolean) {
    super(terraformResource, terraformAttribute, complexObjectIsFromSet, complexObjectIndex);
  }

  public get internalValue(): VoiceServicesCommunicationsGatewayServiceLocation | cdktf.IResolvable | undefined {
    if (this.resolvableValue) {
      return this.resolvableValue;
    }
    let hasAnyValues = this.isEmptyObject;
    const internalValueResult: any = {};
    if (this._allowedMediaSourceAddressPrefixes !== undefined) {
      hasAnyValues = true;
      internalValueResult.allowedMediaSourceAddressPrefixes = this._allowedMediaSourceAddressPrefixes;
    }
    if (this._allowedSignalingSourceAddressPrefixes !== undefined) {
      hasAnyValues = true;
      internalValueResult.allowedSignalingSourceAddressPrefixes = this._allowedSignalingSourceAddressPrefixes;
    }
    if (this._esrpAddresses !== undefined) {
      hasAnyValues = true;
      internalValueResult.esrpAddresses = this._esrpAddresses;
    }
    if (this._location !== undefined) {
      hasAnyValues = true;
      internalValueResult.location = this._location;
    }
    if (this._operatorAddresses !== undefined) {
      hasAnyValues = true;
      internalValueResult.operatorAddresses = this._operatorAddresses;
    }
    return hasAnyValues ? internalValueResult : undefined;
  }

  public set internalValue(value: VoiceServicesCommunicationsGatewayServiceLocation | cdktf.IResolvable | undefined) {
    if (value === undefined) {
      this.isEmptyObject = false;
      this.resolvableValue = undefined;
      this._allowedMediaSourceAddressPrefixes = undefined;
      this._allowedSignalingSourceAddressPrefixes = undefined;
      this._esrpAddresses = undefined;
      this._location = undefined;
      this._operatorAddresses = undefined;
    }
    else if (cdktf.Tokenization.isResolvable(value)) {
      this.isEmptyObject = false;
      this.resolvableValue = value;
    }
    else {
      this.isEmptyObject = Object.keys(value).length === 0;
      this.resolvableValue = undefined;
      this._allowedMediaSourceAddressPrefixes = value.allowedMediaSourceAddressPrefixes;
      this._allowedSignalingSourceAddressPrefixes = value.allowedSignalingSourceAddressPrefixes;
      this._esrpAddresses = value.esrpAddresses;
      this._location = value.location;
      this._operatorAddresses = value.operatorAddresses;
    }
  }

  // allowed_media_source_address_prefixes - computed: false, optional: true, required: false
  private _allowedMediaSourceAddressPrefixes?: string[]; 
  public get allowedMediaSourceAddressPrefixes() {
    return cdktf.Fn.tolist(this.getListAttribute('allowed_media_source_address_prefixes'));
  }
  public set allowedMediaSourceAddressPrefixes(value: string[]) {
    this._allowedMediaSourceAddressPrefixes = value;
  }
  public resetAllowedMediaSourceAddressPrefixes() {
    this._allowedMediaSourceAddressPrefixes = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get allowedMediaSourceAddressPrefixesInput() {
    return this._allowedMediaSourceAddressPrefixes;
  }

  // allowed_signaling_source_address_prefixes - computed: false, optional: true, required: false
  private _allowedSignalingSourceAddressPrefixes?: string[]; 
  public get allowedSignalingSourceAddressPrefixes() {
    return cdktf.Fn.tolist(this.getListAttribute('allowed_signaling_source_address_prefixes'));
  }
  public set allowedSignalingSourceAddressPrefixes(value: string[]) {
    this._allowedSignalingSourceAddressPrefixes = value;
  }
  public resetAllowedSignalingSourceAddressPrefixes() {
    this._allowedSignalingSourceAddressPrefixes = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get allowedSignalingSourceAddressPrefixesInput() {
    return this._allowedSignalingSourceAddressPrefixes;
  }

  // esrp_addresses - computed: false, optional: true, required: false
  private _esrpAddresses?: string[]; 
  public get esrpAddresses() {
    return cdktf.Fn.tolist(this.getListAttribute('esrp_addresses'));
  }
  public set esrpAddresses(value: string[]) {
    this._esrpAddresses = value;
  }
  public resetEsrpAddresses() {
    this._esrpAddresses = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get esrpAddressesInput() {
    return this._esrpAddresses;
  }

  // location - computed: false, optional: false, required: true
  private _location?: string; 
  public get location() {
    return this.getStringAttribute('location');
  }
  public set location(value: string) {
    this._location = value;
  }
  // Temporarily expose input value. Use with caution.
  public get locationInput() {
    return this._location;
  }

  // operator_addresses - computed: false, optional: false, required: true
  private _operatorAddresses?: string[]; 
  public get operatorAddresses() {
    return cdktf.Fn.tolist(this.getListAttribute('operator_addresses'));
  }
  public set operatorAddresses(value: string[]) {
    this._operatorAddresses = value;
  }
  // Temporarily expose input value. Use with caution.
  public get operatorAddressesInput() {
    return this._operatorAddresses;
  }
}

export class VoiceServicesCommunicationsGatewayServiceLocationList extends cdktf.ComplexList {
  public internalValue? : VoiceServicesCommunicationsGatewayServiceLocation[] | cdktf.IResolvable

  /**
  * @param terraformResource The parent resource
  * @param terraformAttribute The attribute on the parent resource this class is referencing
  * @param wrapsSet whether the list is wrapping a set (will add tolist() to be able to access an item via an index)
  */
  constructor(protected terraformResource: cdktf.IInterpolatingParent, protected terraformAttribute: string, protected wrapsSet: boolean) {
    super(terraformResource, terraformAttribute, wrapsSet)
  }

  /**
  * @param index the index of the item to return
  */
  public get(index: number): VoiceServicesCommunicationsGatewayServiceLocationOutputReference {
    return new VoiceServicesCommunicationsGatewayServiceLocationOutputReference(this.terraformResource, this.terraformAttribute, index, this.wrapsSet);
  }
}
export interface VoiceServicesCommunicationsGatewayTimeouts {
  /**
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/azurerm/4.3.0/docs/resources/voice_services_communications_gateway#create VoiceServicesCommunicationsGateway#create}
  */
  readonly create?: string;
  /**
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/azurerm/4.3.0/docs/resources/voice_services_communications_gateway#delete VoiceServicesCommunicationsGateway#delete}
  */
  readonly delete?: string;
  /**
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/azurerm/4.3.0/docs/resources/voice_services_communications_gateway#read VoiceServicesCommunicationsGateway#read}
  */
  readonly read?: string;
  /**
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/azurerm/4.3.0/docs/resources/voice_services_communications_gateway#update VoiceServicesCommunicationsGateway#update}
  */
  readonly update?: string;
}

export function voiceServicesCommunicationsGatewayTimeoutsToTerraform(struct?: VoiceServicesCommunicationsGatewayTimeouts | cdktf.IResolvable): any {
  if (!cdktf.canInspect(struct) || cdktf.Tokenization.isResolvable(struct)) { return struct; }
  if (cdktf.isComplexElement(struct)) {
    throw new Error("A complex element was used as configuration, this is not supported: https://cdk.tf/complex-object-as-configuration");
  }
  return {
    create: cdktf.stringToTerraform(struct!.create),
    delete: cdktf.stringToTerraform(struct!.delete),
    read: cdktf.stringToTerraform(struct!.read),
    update: cdktf.stringToTerraform(struct!.update),
  }
}


export function voiceServicesCommunicationsGatewayTimeoutsToHclTerraform(struct?: VoiceServicesCommunicationsGatewayTimeouts | cdktf.IResolvable): any {
  if (!cdktf.canInspect(struct) || cdktf.Tokenization.isResolvable(struct)) { return struct; }
  if (cdktf.isComplexElement(struct)) {
    throw new Error("A complex element was used as configuration, this is not supported: https://cdk.tf/complex-object-as-configuration");
  }
  const attrs = {
    create: {
      value: cdktf.stringToHclTerraform(struct!.create),
      isBlock: false,
      type: "simple",
      storageClassType: "string",
    },
    delete: {
      value: cdktf.stringToHclTerraform(struct!.delete),
      isBlock: false,
      type: "simple",
      storageClassType: "string",
    },
    read: {
      value: cdktf.stringToHclTerraform(struct!.read),
      isBlock: false,
      type: "simple",
      storageClassType: "string",
    },
    update: {
      value: cdktf.stringToHclTerraform(struct!.update),
      isBlock: false,
      type: "simple",
      storageClassType: "string",
    },
  };

  // remove undefined attributes
  return Object.fromEntries(Object.entries(attrs).filter(([_, value]) => value !== undefined && value.value !== undefined));
}

export class VoiceServicesCommunicationsGatewayTimeoutsOutputReference extends cdktf.ComplexObject {
  private isEmptyObject = false;
  private resolvableValue?: cdktf.IResolvable;

  /**
  * @param terraformResource The parent resource
  * @param terraformAttribute The attribute on the parent resource this class is referencing
  */
  public constructor(terraformResource: cdktf.IInterpolatingParent, terraformAttribute: string) {
    super(terraformResource, terraformAttribute, false);
  }

  public get internalValue(): VoiceServicesCommunicationsGatewayTimeouts | cdktf.IResolvable | undefined {
    if (this.resolvableValue) {
      return this.resolvableValue;
    }
    let hasAnyValues = this.isEmptyObject;
    const internalValueResult: any = {};
    if (this._create !== undefined) {
      hasAnyValues = true;
      internalValueResult.create = this._create;
    }
    if (this._delete !== undefined) {
      hasAnyValues = true;
      internalValueResult.delete = this._delete;
    }
    if (this._read !== undefined) {
      hasAnyValues = true;
      internalValueResult.read = this._read;
    }
    if (this._update !== undefined) {
      hasAnyValues = true;
      internalValueResult.update = this._update;
    }
    return hasAnyValues ? internalValueResult : undefined;
  }

  public set internalValue(value: VoiceServicesCommunicationsGatewayTimeouts | cdktf.IResolvable | undefined) {
    if (value === undefined) {
      this.isEmptyObject = false;
      this.resolvableValue = undefined;
      this._create = undefined;
      this._delete = undefined;
      this._read = undefined;
      this._update = undefined;
    }
    else if (cdktf.Tokenization.isResolvable(value)) {
      this.isEmptyObject = false;
      this.resolvableValue = value;
    }
    else {
      this.isEmptyObject = Object.keys(value).length === 0;
      this.resolvableValue = undefined;
      this._create = value.create;
      this._delete = value.delete;
      this._read = value.read;
      this._update = value.update;
    }
  }

  // create - computed: false, optional: true, required: false
  private _create?: string; 
  public get create() {
    return this.getStringAttribute('create');
  }
  public set create(value: string) {
    this._create = value;
  }
  public resetCreate() {
    this._create = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get createInput() {
    return this._create;
  }

  // delete - computed: false, optional: true, required: false
  private _delete?: string; 
  public get delete() {
    return this.getStringAttribute('delete');
  }
  public set delete(value: string) {
    this._delete = value;
  }
  public resetDelete() {
    this._delete = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get deleteInput() {
    return this._delete;
  }

  // read - computed: false, optional: true, required: false
  private _read?: string; 
  public get read() {
    return this.getStringAttribute('read');
  }
  public set read(value: string) {
    this._read = value;
  }
  public resetRead() {
    this._read = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get readInput() {
    return this._read;
  }

  // update - computed: false, optional: true, required: false
  private _update?: string; 
  public get update() {
    return this.getStringAttribute('update');
  }
  public set update(value: string) {
    this._update = value;
  }
  public resetUpdate() {
    this._update = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get updateInput() {
    return this._update;
  }
}

/**
* Represents a {@link https://registry.terraform.io/providers/hashicorp/azurerm/4.3.0/docs/resources/voice_services_communications_gateway azurerm_voice_services_communications_gateway}
*/
export class VoiceServicesCommunicationsGateway extends cdktf.TerraformResource {

  // =================
  // STATIC PROPERTIES
  // =================
  public static readonly tfResourceType = "azurerm_voice_services_communications_gateway";

  // ==============
  // STATIC Methods
  // ==============
  /**
  * Generates CDKTF code for importing a VoiceServicesCommunicationsGateway resource upon running "cdktf plan <stack-name>"
  * @param scope The scope in which to define this construct
  * @param importToId The construct id used in the generated config for the VoiceServicesCommunicationsGateway to import
  * @param importFromId The id of the existing VoiceServicesCommunicationsGateway that should be imported. Refer to the {@link https://registry.terraform.io/providers/hashicorp/azurerm/4.3.0/docs/resources/voice_services_communications_gateway#import import section} in the documentation of this resource for the id to use
  * @param provider? Optional instance of the provider where the VoiceServicesCommunicationsGateway to import is found
  */
  public static generateConfigForImport(scope: Construct, importToId: string, importFromId: string, provider?: cdktf.TerraformProvider) {
        return new cdktf.ImportableResource(scope, importToId, { terraformResourceType: "azurerm_voice_services_communications_gateway", importId: importFromId, provider });
      }

  // ===========
  // INITIALIZER
  // ===========

  /**
  * Create a new {@link https://registry.terraform.io/providers/hashicorp/azurerm/4.3.0/docs/resources/voice_services_communications_gateway azurerm_voice_services_communications_gateway} Resource
  *
  * @param scope The scope in which to define this construct
  * @param id The scoped construct ID. Must be unique amongst siblings in the same scope
  * @param options VoiceServicesCommunicationsGatewayConfig
  */
  public constructor(scope: Construct, id: string, config: VoiceServicesCommunicationsGatewayConfig) {
    super(scope, id, {
      terraformResourceType: 'azurerm_voice_services_communications_gateway',
      terraformGeneratorMetadata: {
        providerName: 'azurerm',
        providerVersion: '4.3.0',
        providerVersionConstraint: '~> 4.0'
      },
      provider: config.provider,
      dependsOn: config.dependsOn,
      count: config.count,
      lifecycle: config.lifecycle,
      provisioners: config.provisioners,
      connection: config.connection,
      forEach: config.forEach
    });
    this._apiBridge = config.apiBridge;
    this._autoGeneratedDomainNameLabelScope = config.autoGeneratedDomainNameLabelScope;
    this._codecs = config.codecs;
    this._connectivity = config.connectivity;
    this._e911Type = config.e911Type;
    this._emergencyDialStrings = config.emergencyDialStrings;
    this._id = config.id;
    this._location = config.location;
    this._microsoftTeamsVoicemailPilotNumber = config.microsoftTeamsVoicemailPilotNumber;
    this._name = config.name;
    this._onPremMcpEnabled = config.onPremMcpEnabled;
    this._platforms = config.platforms;
    this._resourceGroupName = config.resourceGroupName;
    this._tags = config.tags;
    this._serviceLocation.internalValue = config.serviceLocation;
    this._timeouts.internalValue = config.timeouts;
  }

  // ==========
  // ATTRIBUTES
  // ==========

  // api_bridge - computed: false, optional: true, required: false
  private _apiBridge?: string; 
  public get apiBridge() {
    return this.getStringAttribute('api_bridge');
  }
  public set apiBridge(value: string) {
    this._apiBridge = value;
  }
  public resetApiBridge() {
    this._apiBridge = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get apiBridgeInput() {
    return this._apiBridge;
  }

  // auto_generated_domain_name_label_scope - computed: false, optional: true, required: false
  private _autoGeneratedDomainNameLabelScope?: string; 
  public get autoGeneratedDomainNameLabelScope() {
    return this.getStringAttribute('auto_generated_domain_name_label_scope');
  }
  public set autoGeneratedDomainNameLabelScope(value: string) {
    this._autoGeneratedDomainNameLabelScope = value;
  }
  public resetAutoGeneratedDomainNameLabelScope() {
    this._autoGeneratedDomainNameLabelScope = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get autoGeneratedDomainNameLabelScopeInput() {
    return this._autoGeneratedDomainNameLabelScope;
  }

  // codecs - computed: false, optional: false, required: true
  private _codecs?: string; 
  public get codecs() {
    return this.getStringAttribute('codecs');
  }
  public set codecs(value: string) {
    this._codecs = value;
  }
  // Temporarily expose input value. Use with caution.
  public get codecsInput() {
    return this._codecs;
  }

  // connectivity - computed: false, optional: false, required: true
  private _connectivity?: string; 
  public get connectivity() {
    return this.getStringAttribute('connectivity');
  }
  public set connectivity(value: string) {
    this._connectivity = value;
  }
  // Temporarily expose input value. Use with caution.
  public get connectivityInput() {
    return this._connectivity;
  }

  // e911_type - computed: false, optional: false, required: true
  private _e911Type?: string; 
  public get e911Type() {
    return this.getStringAttribute('e911_type');
  }
  public set e911Type(value: string) {
    this._e911Type = value;
  }
  // Temporarily expose input value. Use with caution.
  public get e911TypeInput() {
    return this._e911Type;
  }

  // emergency_dial_strings - computed: false, optional: true, required: false
  private _emergencyDialStrings?: string[]; 
  public get emergencyDialStrings() {
    return this.getListAttribute('emergency_dial_strings');
  }
  public set emergencyDialStrings(value: string[]) {
    this._emergencyDialStrings = value;
  }
  public resetEmergencyDialStrings() {
    this._emergencyDialStrings = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get emergencyDialStringsInput() {
    return this._emergencyDialStrings;
  }

  // id - computed: true, optional: true, required: false
  private _id?: string; 
  public get id() {
    return this.getStringAttribute('id');
  }
  public set id(value: string) {
    this._id = value;
  }
  public resetId() {
    this._id = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get idInput() {
    return this._id;
  }

  // location - computed: false, optional: false, required: true
  private _location?: string; 
  public get location() {
    return this.getStringAttribute('location');
  }
  public set location(value: string) {
    this._location = value;
  }
  // Temporarily expose input value. Use with caution.
  public get locationInput() {
    return this._location;
  }

  // microsoft_teams_voicemail_pilot_number - computed: false, optional: true, required: false
  private _microsoftTeamsVoicemailPilotNumber?: string; 
  public get microsoftTeamsVoicemailPilotNumber() {
    return this.getStringAttribute('microsoft_teams_voicemail_pilot_number');
  }
  public set microsoftTeamsVoicemailPilotNumber(value: string) {
    this._microsoftTeamsVoicemailPilotNumber = value;
  }
  public resetMicrosoftTeamsVoicemailPilotNumber() {
    this._microsoftTeamsVoicemailPilotNumber = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get microsoftTeamsVoicemailPilotNumberInput() {
    return this._microsoftTeamsVoicemailPilotNumber;
  }

  // name - computed: false, optional: false, required: true
  private _name?: string; 
  public get name() {
    return this.getStringAttribute('name');
  }
  public set name(value: string) {
    this._name = value;
  }
  // Temporarily expose input value. Use with caution.
  public get nameInput() {
    return this._name;
  }

  // on_prem_mcp_enabled - computed: false, optional: true, required: false
  private _onPremMcpEnabled?: boolean | cdktf.IResolvable; 
  public get onPremMcpEnabled() {
    return this.getBooleanAttribute('on_prem_mcp_enabled');
  }
  public set onPremMcpEnabled(value: boolean | cdktf.IResolvable) {
    this._onPremMcpEnabled = value;
  }
  public resetOnPremMcpEnabled() {
    this._onPremMcpEnabled = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get onPremMcpEnabledInput() {
    return this._onPremMcpEnabled;
  }

  // platforms - computed: false, optional: false, required: true
  private _platforms?: string[]; 
  public get platforms() {
    return this.getListAttribute('platforms');
  }
  public set platforms(value: string[]) {
    this._platforms = value;
  }
  // Temporarily expose input value. Use with caution.
  public get platformsInput() {
    return this._platforms;
  }

  // resource_group_name - computed: false, optional: false, required: true
  private _resourceGroupName?: string; 
  public get resourceGroupName() {
    return this.getStringAttribute('resource_group_name');
  }
  public set resourceGroupName(value: string) {
    this._resourceGroupName = value;
  }
  // Temporarily expose input value. Use with caution.
  public get resourceGroupNameInput() {
    return this._resourceGroupName;
  }

  // tags - computed: false, optional: true, required: false
  private _tags?: { [key: string]: string }; 
  public get tags() {
    return this.getStringMapAttribute('tags');
  }
  public set tags(value: { [key: string]: string }) {
    this._tags = value;
  }
  public resetTags() {
    this._tags = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get tagsInput() {
    return this._tags;
  }

  // service_location - computed: false, optional: false, required: true
  private _serviceLocation = new VoiceServicesCommunicationsGatewayServiceLocationList(this, "service_location", true);
  public get serviceLocation() {
    return this._serviceLocation;
  }
  public putServiceLocation(value: VoiceServicesCommunicationsGatewayServiceLocation[] | cdktf.IResolvable) {
    this._serviceLocation.internalValue = value;
  }
  // Temporarily expose input value. Use with caution.
  public get serviceLocationInput() {
    return this._serviceLocation.internalValue;
  }

  // timeouts - computed: false, optional: true, required: false
  private _timeouts = new VoiceServicesCommunicationsGatewayTimeoutsOutputReference(this, "timeouts");
  public get timeouts() {
    return this._timeouts;
  }
  public putTimeouts(value: VoiceServicesCommunicationsGatewayTimeouts) {
    this._timeouts.internalValue = value;
  }
  public resetTimeouts() {
    this._timeouts.internalValue = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get timeoutsInput() {
    return this._timeouts.internalValue;
  }

  // =========
  // SYNTHESIS
  // =========

  protected synthesizeAttributes(): { [name: string]: any } {
    return {
      api_bridge: cdktf.stringToTerraform(this._apiBridge),
      auto_generated_domain_name_label_scope: cdktf.stringToTerraform(this._autoGeneratedDomainNameLabelScope),
      codecs: cdktf.stringToTerraform(this._codecs),
      connectivity: cdktf.stringToTerraform(this._connectivity),
      e911_type: cdktf.stringToTerraform(this._e911Type),
      emergency_dial_strings: cdktf.listMapper(cdktf.stringToTerraform, false)(this._emergencyDialStrings),
      id: cdktf.stringToTerraform(this._id),
      location: cdktf.stringToTerraform(this._location),
      microsoft_teams_voicemail_pilot_number: cdktf.stringToTerraform(this._microsoftTeamsVoicemailPilotNumber),
      name: cdktf.stringToTerraform(this._name),
      on_prem_mcp_enabled: cdktf.booleanToTerraform(this._onPremMcpEnabled),
      platforms: cdktf.listMapper(cdktf.stringToTerraform, false)(this._platforms),
      resource_group_name: cdktf.stringToTerraform(this._resourceGroupName),
      tags: cdktf.hashMapper(cdktf.stringToTerraform)(this._tags),
      service_location: cdktf.listMapper(voiceServicesCommunicationsGatewayServiceLocationToTerraform, true)(this._serviceLocation.internalValue),
      timeouts: voiceServicesCommunicationsGatewayTimeoutsToTerraform(this._timeouts.internalValue),
    };
  }

  protected synthesizeHclAttributes(): { [name: string]: any } {
    const attrs = {
      api_bridge: {
        value: cdktf.stringToHclTerraform(this._apiBridge),
        isBlock: false,
        type: "simple",
        storageClassType: "string",
      },
      auto_generated_domain_name_label_scope: {
        value: cdktf.stringToHclTerraform(this._autoGeneratedDomainNameLabelScope),
        isBlock: false,
        type: "simple",
        storageClassType: "string",
      },
      codecs: {
        value: cdktf.stringToHclTerraform(this._codecs),
        isBlock: false,
        type: "simple",
        storageClassType: "string",
      },
      connectivity: {
        value: cdktf.stringToHclTerraform(this._connectivity),
        isBlock: false,
        type: "simple",
        storageClassType: "string",
      },
      e911_type: {
        value: cdktf.stringToHclTerraform(this._e911Type),
        isBlock: false,
        type: "simple",
        storageClassType: "string",
      },
      emergency_dial_strings: {
        value: cdktf.listMapperHcl(cdktf.stringToHclTerraform, false)(this._emergencyDialStrings),
        isBlock: false,
        type: "list",
        storageClassType: "stringList",
      },
      id: {
        value: cdktf.stringToHclTerraform(this._id),
        isBlock: false,
        type: "simple",
        storageClassType: "string",
      },
      location: {
        value: cdktf.stringToHclTerraform(this._location),
        isBlock: false,
        type: "simple",
        storageClassType: "string",
      },
      microsoft_teams_voicemail_pilot_number: {
        value: cdktf.stringToHclTerraform(this._microsoftTeamsVoicemailPilotNumber),
        isBlock: false,
        type: "simple",
        storageClassType: "string",
      },
      name: {
        value: cdktf.stringToHclTerraform(this._name),
        isBlock: false,
        type: "simple",
        storageClassType: "string",
      },
      on_prem_mcp_enabled: {
        value: cdktf.booleanToHclTerraform(this._onPremMcpEnabled),
        isBlock: false,
        type: "simple",
        storageClassType: "boolean",
      },
      platforms: {
        value: cdktf.listMapperHcl(cdktf.stringToHclTerraform, false)(this._platforms),
        isBlock: false,
        type: "list",
        storageClassType: "stringList",
      },
      resource_group_name: {
        value: cdktf.stringToHclTerraform(this._resourceGroupName),
        isBlock: false,
        type: "simple",
        storageClassType: "string",
      },
      tags: {
        value: cdktf.hashMapperHcl(cdktf.stringToHclTerraform)(this._tags),
        isBlock: false,
        type: "map",
        storageClassType: "stringMap",
      },
      service_location: {
        value: cdktf.listMapperHcl(voiceServicesCommunicationsGatewayServiceLocationToHclTerraform, true)(this._serviceLocation.internalValue),
        isBlock: true,
        type: "set",
        storageClassType: "VoiceServicesCommunicationsGatewayServiceLocationList",
      },
      timeouts: {
        value: voiceServicesCommunicationsGatewayTimeoutsToHclTerraform(this._timeouts.internalValue),
        isBlock: true,
        type: "struct",
        storageClassType: "VoiceServicesCommunicationsGatewayTimeouts",
      },
    };

    // remove undefined attributes
    return Object.fromEntries(Object.entries(attrs).filter(([_, value]) => value !== undefined && value.value !== undefined ))
  }
}
